### ISSUE TITLE
alexa: Error: listen EACCES 0.0.0.0:80

### ISSUE THREAD

**Issue by damooooooooooh** [tim-hellhake/alexa-adapter#1]
Not able to start the alexa adapter, stack trace below.  Port 80 taken by the gateway?

> alexa: Error: listen EACCES 0.0.0.0:80
> alexa:     at Server.setupListenHandle [as _listen2] (net.js:1343:19)
> alexa:     at listenInCluster (net.js:1401:12)
> alexa:     at Server.listen (net.js:1485:7)
> alexa:     at Function.listen (/home/pi/.mozilla-iot/addons/alexa-adapter/node_modules/express/lib/application.js:618:24)
> alexa:     at HueBridgeEmulator.start (/home/pi/.mozilla-iot/addons/alexa-adapter/node_modules/hue-bridge-emulator/hue-bridge-emulator.js:120:32)
> alexa:     at new AlexaDevice (/home/pi/.mozilla-iot/addons/alexa-adapter/alexa-adapter.js:30:23)
> alexa:     at new AlexaAdapter (/home/pi/.mozilla-iot/addons/alexa-adapter/alexa-adapter.js:93:20)
> alexa:     at module.exports (/home/pi/.mozilla-iot/addons/alexa-adapter/index.js:12:33)
> alexa:     at pluginClientPromise.then (/home/pi/mozilla-iot/gateway/src/addon-loader.js:113:7)
> alexa:     at <anonymous>

**Comment by tim-hellhake** [comment]
> Port 80 taken by the gateway?

Indeed.
The problem is the Echo won't let me use another port so the addon is not usable at the moment.
